steps:
 - name: 'docker'
   args: ['build','-t','gcr.io/$PROJECT_ID/gcp-devops-project','.']
# push container image
 - name: "gcr.io/cloud-builders/docker"
   args: ["push","gcr.io/$PROJECT_ID/gcp-devops-project"]
# Deploy container image to GKE
 - name: "gcr.io/cloud-builders/gke-deploy"
   args:
   - run
   - --filename=gke.yaml
   - --image=gcr.io/$PROJECT_ID/gcp-devops-project
   - --location=us-central1-c
   - --cluster=my-gcp-cluster
   - --namespace=gcp-devops-prod